apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cloudnative-pg-operator-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cpaas-cloudnativepg-operator
  project: default
  source:
    path: charts/cloudnative-pg
    repoURL: https://github.com/Th3Lourde/cnpg-argo
    targetRevision: main
    helm:
      valueFiles:
        - values-local-argo.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
